sudo: required
services:
    - docker


before_install:
    - docker build -t pipaliyaatul/frontendreactapp -f Dockerfile.dev .

script:
    - docker run -e CI=true pipaliyaatul/frontendreactapp npm run test -- --coverage


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: docker-react-frontapp
    env: DockerReactFrontapp-env
    bucket_name: "elasticbeanstalk-us-east-2-847049386041"
    bucket_path: "docker-react-frontapp"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"

