sudo: required
services:
    - docker


before_install:
    - docker build -t pipaliyaatul/frontendreactapp -f Dockerfile.dev .

script:
    - docker run -e CI=true pipaliyaatul/frontendreactapp npm run test -- --coverage

